### ISSUE TITLE
Add Test sharding

### ISSUE THREAD

**Issue by bootstraponline** [instructure/flank#2]
Add test sharding support based on JUnit Runners shards.

> -e numShards 4 -e shardIndex 1 
> https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner.html

This will be more stable than trying to time individual tests on Firebase.

**Comment by bootstraponline** [comment]
Native sharding is a mess and doesn't work.

`(Math.abs(description.hashCode()) % mNumShards) == mShardIndex;` leads to random crashes.

```bash
adb shell "CLASSPATH=\$(pm path android.support.test.services) app_process / android.support.test.services.shellexecutor.ShellMain am instrument -r -w -e targetInstrumentation com.example.app.test/android.support.test.runner.AndroidJUnitRunner   -e debug false -e class 'com.example.app.ExampleUiTest' -e numShards 2 -e shardIndex 3 android.support.test.orchestrator/android.support.test.orchestrator.AndroidTestOrchestrator"

# -e numShards 0 -e shardIndex 0
# OK (2 tests)

# -e numShards 1 -e shardIndex 0
# OK (2 tests)

# -e numShards 2 -e shardIndex 0
# java.lang.ClassNotFoundException

# -e numShards 2 -e shardIndex 1
# OK (2 tests)

# 1) no tests found
# java.lang.ClassNotFoundException: Invalid name: no tests found
# 	at java.lang.Class.classForName(Native Method)
# 	at java.lang.Class.forName(Class.java:453)
# 	at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
# 	at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
# 	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:775)
# 	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:537)
# 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:383)
# 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
```

**Comment by bootstraponline** [comment]
chunked sharding: https://github.com/instructure/flank/commit/cd5668a2170f04d2ec741912d30045e4b600da74
